### ISSUE TITLE
계속 0개의 링크를 찾았다고만 나옵니다.

### ISSUE THREAD

**Issue by kide4869** [yeorinhieut/novel-dl#1]
해결방법이 있을까요? 질문드려 봅니다. 사이트 로그인도 해뒀습니다.
<img width="848" alt="스크린샷 2023-11-26 190436" src="https://github.com/yeorinhieut/novel-dl/assets/152063424/d025b746-273a-4f68-9eb0-3b03dc411540">

**Comment by yeorinhieut** [comment]
Checking Issues

**Comment by yeorinhieut** [comment]
북토끼가 요상하게 사이트 구조를 변경한것 같습니다.
브라우저를 통한 접근이 아니면 빠꾸먹이네요.
곧 패치하겠습니다.

**Comment by Damnuuu** [comment]
저도 같은 증상입니다. 패치를 기다립니다.
혹시 다운로드 목록도 가능할까요?
미리 다운 받을 목록을 입력해놓으면 순차적으로 받을수 있는 기능은 어려울까요?

**Comment by yeorinhieut** [comment]
캡챠를 우회하긴 어려울듯 해서
정상적으로 접근한 페이지

**Comment by yeorinhieut** [comment]
https://github.com/yeorinhieut/novel-dl/releases/tag/v0.1.2

수정하였습니다.
소설 목록에서 ctrl + s 를 이용하여 html 파일을 수동으로 다운로드하고,
프로그램과 같은 경로에 page.html 로 저장하시면 자동으로 그 파일을 감지하려 실행됩니다
