### ISSUE TITLE
파일 병합 시 100화부터 병합됩니다

### ISSUE THREAD

**Issue by sususu77** [yeorinhieut/novel-dl#10]
추출하고 마지막에 파일 병합을 물을 때 y를 누르면 
예전에는 1~마지막편까지 병합했는데 근래에는 자꾸 100화부터 저장되고 중간 회차도 엉킵니다
해결 방법이 있을까요?

**Comment by yeorinhieut** [comment]
병합 기능은 단순히 output에 있는 모든 파일을 병합하는 기능이라 output에 이미 파일들이 있는 경우 문제가 발생할 수 있습니다. 체크 부탁드립니다!

**Comment by sususu77** [comment]
output에 방금 다운받은 작품 1~마지막화까지만 있는 상태인데도 그럴 경우에는 혹시 어떤 방법을 시도해 봐야 할까요? ㅠ

**Comment by wheatflor** [comment]
이 문제 저도 겪었는데 
1. 원본 사이트 목차 이름 자체가 엉망으로 지어져있는경우.
(애초에 정렬이 되는순간 엉망이되는경우)
2. 목차 넘버링이 001 002.. 가 아니라 1 2 ....같이 되어있어서 순서에 오류가 생기는경우 
(숫자를 따로 추출해서 정렬 후 병합하는게 아니라 문자열 방식으로 정렬된걸 병합해서 생기는 문제)
더라고요.

이 유형에 속해도 가끔 잘 정렬된 상태로 병합되는경우도 있긴했는데, 잘되는 이유는 모르겠더라고요.
2번유형은 병합이 잘되는 경우가 더 많아서 왜그러지 싶더라고요.
1번유형은 애초에 그런 작품이 몇 개 없다보니 전부 문제가 발생했고요.
 

2번 유형의 경우 따로이름 바꿀거없이 파워쉘로 텍스트 정렬방식 바꾼다음 병합하는거 만들어서 실행시키면 해결되다보니 그거 만들어두고 쓰고있긴한데 
근본적인 해결을 위해선 텍스트파일 이름 생성규칙을 '회차번호(자릿수맞춤or4자리수) 회차명'으로 하는게 확실하긴 할거같네요.

**Comment by yeorinhieut** [comment]
감사합니다! 반영하여 다음 릴리즈에 업데이트 하도록 하겠습니다

**Comment by yeorinhieut** [comment]
새로운 릴리즈에 해결되었습니다. 사용 방법 역시 변경되었으니 readme 참고해주세요.
