### ISSUE TITLE
안녕하세요

### ISSUE THREAD

**Issue by beginner1444** [yeorinhieut/novel-dl#11]
검색하다가 여기까지 찾아왔습니다 선생님
혹시 저거 프로그램 받아서 그냥 실행만 눌러도 되는건가요?
주소랑 회차랑 y 눌러서 다 했는데 결과물이 없네요 ㅠ

**Comment by beginner1444** [comment]
novel-dl_windows_x64
다운 후에 설명대로 했는데 빈 텍스트 문서만 만들어집니다 ㅜ

**Comment by yeorinhieut** [comment]
자세한 설명 부탁드립니다. 단편적인 정보로는 오류를 추정할 수 없습니다.
혹은 html 파일을 직접 임포트해서 시도해보시길 바랍니다.

**Comment by yeorinhieut** [comment]
v0.2.0 이 릴리즈 되었습니다.
해당 릴리즈에서도 동일한 이슈가 발생하면, 다시 이슈를 open 해주세요.
