### ISSUE TITLE
표지 없는 목록에 공통적으로 발생하는 증상.

### ISSUE THREAD

**Issue by turquoiselight** [yeorinhieut/novel-dl#12]
(cover)표지 이미지가 없는 파일 다운로드 불가 증상이 있네요.

소설의 마지막 회차 번호를 입력하세요: 410
다운로드를 시작하시겠습니까? (y/n): y
다운로드할 스레드 수를 입력하세요 (일반적으로 1을 권장합니다): 1
0개의 링크를 찾았습니다.
0 [__________________________________________________________________________________________________________] ?% ? p/s
다운로드가 완료되었습니다.
다운로드한 파일을 하나의 txt 파일로 병합하시겠습니까? (y/n):

표지 이미지가 없는 파일 다운로드가 위 방식으로 공통적으로 안 되는 증상이 보입니다.
0개의 링크에 관련해서 html을 이용한 방식으로 시도도 해봤으나 마찬가지였네요.

해결 가능할까 이슈에 남겨봅니다.

**Comment by yeorinhieut** [comment]
소설 회차 링크 부탁드립니다

**Comment by yeorinhieut** [comment]
v0.2.0 이 릴리즈 되었습니다.
해당 릴리즈에서도 동일한 이슈가 발생하면, 다시 이슈를 open 해주세요.
