### ISSUE TITLE
파일 병합시 개행 추가

### ISSUE THREAD

**Issue by garlicbad** [yeorinhieut/novel-dl#13]
파일 병합할 때 바로 붙이는 게 아니라 새 라인을 하나 추가할 수 있는 옵션이 있으면 좋겠습니다.

> ...
> 이미 가을이었다. 밤이면 제법 쌀쌀했고, 특히 산속은 더욱 그러했다. 한제는 잠결에 몸을 웅크렸다. 그렇게 밤은 지나갔다.
> 5화 절벽 아래로
> ...

불여진 회차가 새 문단으로 보이지 않아서 가독성이 조금 떨어지네요.

**Comment by yeorinhieut** [comment]
기본적으로 새 개행을 추가해서 병합하도록 소스를 수정하겠습니다.
좋은 제보 감사합니다

**Comment by yeorinhieut** [comment]
혹시 v0.5.0 사용시 발생한 증상인가요?
