### ISSUE TITLE
에피소드간 공백관련

### ISSUE THREAD

**Issue by wheatflor** [yeorinhieut/novel-dl#16]
각 에피소드 사이의 그 빈칸이 줄바꿈만 있는게 아니라 공백문자도 이상하게 많이 있어서 의도한 사항이 아닌거 같기도하고, 너무 넓어서 불편해서 저는 이렇게 수정해서 쓰고있는데요.
  
(원래코드)
function cleanText(text) {
    text = text.replace(/<div>/g, '');
    text = text.replace(/<\/div>/g, '');
    text = text.replace(/<p>/g, '\n');
    text = text.replace(/<\/p>/g, '\n');
    text = text.replace(/<br\s*[/]?>/g, '\n');
    text = text.replace(/<[^>]*>/g, '');
    text = unescapeHTML(text);
    return text;
  }

(수정코드)
  function cleanText(text) {
    text = text.replace(/<div>/g, '');
    text = text.replace(/<\/div>/g, '');
    text = text.replace(/<p>/g, '\n');
    text = text.replace(/<\/p>/g, '\n');
    text = text.replace(/<br\s*[/]?>/g, '\n');
    text = text.replace(/<[^>]*>/g, '');
    text = unescapeHTML(text);
    text = text.replace(/ {2,}/g, ''); //추가됨 (2개이상공백 삭제)
    text = text.replace(/\n{2,}/g, '\n\n'); //추가됨 (2개이상 개행문자 두개로변경)
    return text;
  }

이렇게하면 에피소드 사이에 세개의 빈줄이 생깁니다.

별상관은 없지만 2개이상의 개행문자를 변경하는 항목에서  \n의 개수를 늘리면 에피소드 사이에 2n+1개의 빈줄이 생기더라고요.

추후 코드수정에 참고가 되었으면 하네요.

아 그런데 이런글 적는게 불편하거나 귀찮으시면 바로 말해주세요.
솔직히 코딩을 제대로 할줄아는건 아니라 괜히 방해만 될 수도 있는 수준이라 
쓸 때마다 귀찮아하시면 어쩌지..라는 고민을 안해도 돼서 칼같이 말해주시는편이 저도 행복합니다.

**Comment by yeorinhieut** [comment]
언제든지 의견과 기여는 좋습니다.
저 부분은 혹시 회차에 엔터가 여러번 의도적으로 사용된 부분이 있을까봐 고민중인 부분이였는데, 적당히 3칸 이상 공백시 1칸으로 변경하면 될듯 합니다.

추후 릴리즈에 반영하겠습니다. 감사합니다
