### ISSUE TITLE
북마크이용 하면 클릭시 새탭으로  열리면서 작동이 안되는거 같습니다

### ISSUE THREAD

**Issue by kcysp** [yeorinhieut/novel-dl#17]
북마크 클릭시 새탭으로 열린후 f12 눌러서 콘솔들어가면  "This script should be run on the novel episode list page"
이라고 뜸니다 (네이버웨일 사용합니다)

혹시 제가 놓친부분이 있어서 안되는 걸까요?? ㅜㅜ

**Comment by yeorinhieut** [comment]
북마크 클릭시 새탭으로 이동한다는게 어떠한 의미일까요?
소설 회차 페이지에서 클릭시 소설 회차 페이지 내에서 작동하는게 정상입니다.

웨일의 경우 테스트해보지 않았으나,
한번 ctrl+shift+i 를 눌러 콘솔에서 script.js를 붙여넣어서 실행해 보세요.

북마크 역시 페이지 내에서 실행이 되나 체크해 주세요.

**Comment by yeorinhieut** [comment]
https://forum.whale.naver.com/topic/42207/
참고해 주세요.

**Comment by kcysp** [comment]
> https://forum.whale.naver.com/topic/42207/ 참고해 주세요.

아 감사합니다 이놈이 범인이었네요 

너무 작동이 잘됩니다~~ 따로 프로그램 필요없이 북마크에서 작동하니 편하네요
