### ISSUE TITLE
줄내림이 안된 상태로 나옵니다.

### ISSUE THREAD

**Issue by wuwueo** [yeorinhieut/novel-dl#2]
![1](https://github.com/yeorinhieut/novel-dl/assets/152704192/eff8581b-5af3-4c85-a291-be82148ff199)
![2](https://github.com/yeorinhieut/novel-dl/assets/152704192/6241a4fb-e97e-43b2-863c-114f73b7d415)

원본글에는 줄내림 되어있는 상태인데, 텍스트 파일에는 줄내림 없는 상태로 나옵니다.

전부 이러는 건 아니고 일부에 한해서 해당 증상이 나오는데, 어떤 건 모든 회차가 전부 이렇게 나오고, 또 어떤 건 일정 회차만 이렇게 나오기도 합니다.

혹시 해결 방법이 있을까요?

**Comment by yeorinhieut** [comment]
인지하였습니다. 혹시 회차 링크 주실 수 있나요?

**Comment by yeorinhieut** [comment]
https://github.com/yeorinhieut/novel-dl/releases/tag/v0.1.2

수정하였습니다.
