### ISSUE TITLE
1000회 이상 되는 경우

### ISSUE THREAD

**Issue by pkkong** [yeorinhieut/novel-dl#20]
안녕하세요
먼저 좋은 소스 제공에 감사드립니다.

Java 이용해서 받는 경우 1,000회 이상인 소설의 경우 받기가 힘든데
어떻게 수정해서 사용해야 할까요??

다시 한 번 감사합니다

**Comment by yeorinhieut** [comment]
1000회차 이상 소설이라
페이지가 나뉘어져서 받지 못하는 경우 => 각각의 페이지마다 사용해서 임시방편으로 다운 가능합니다.

코드 자체의 오류가 발생하는 경우 알려주시면 감사하겠습니다.

**Comment by pkkong** [comment]
넵 감사합니다

**Comment by yeorinhieut** [comment]
v1.0.0 릴리즈에 다중 페이지 지원 기능을 추가하였습니다.

**Comment by pkkong** [comment]
> v1.0.0 릴리즈에 다중 페이지 지원 기능을 추가하였습니다.

 감사합니다 :)
