### ISSUE TITLE
1000회가 넘어가는 소설 다운로드 방법이 궁금합니다.

### ISSUE THREAD

**Issue by ghlower** [yeorinhieut/novel-dl#21]
안녕하세요. 우연찮게 검색으로 알게되어 잘 사용하고 있습니다.

가끔 1000 에피소드가 넘어가는 녀석들이 있는데 1001화 부터는 어떻게 다운로드를 할 수 있는지 알고싶습니다.

감사합니다.

**Comment by yeorinhieut** [comment]
1000회차 이상 소설이라
페이지가 나뉘어져서 받지 못하는 경우 => 각각의 페이지마다 사용해서 임시방편으로 다운 가능합니다.

코드 자체의 오류가 발생하는 경우 알려주시면 감사하겠습니다.

**Comment by yeorinhieut** [comment]
v1.0.0 릴리즈에 다중 페이지 지원 기능을 추가하였습니다.
