### ISSUE TITLE
화수가 많을경우 오류가 발생합니다.

### ISSUE THREAD

**Issue by shootmg50** [yeorinhieut/novel-dl#22]
좋은프로그램 감사합니다. 너무 잘 쓰고 있습니다.
다름이 아니라 소설 연재 차수가  긴 소설의 경우 (1000편이상)
목록페이지가 여러개라 마지막 페이지만 통합되어서 다운로드 됩니다.
다시한번 좋은 프로그램 만들어 주셔서 감사합니다. 고맙습니다.

**Comment by yeorinhieut** [comment]
1000회차 이상 소설이라
페이지가 나뉘어져서 받지 못하는 경우 => 각각의 페이지마다 사용해서 임시방편으로 다운 가능합니다.

코드 자체의 오류가 발생하는 경우 알려주시면 감사하겠습니다.

**Comment by dmswkaql** [comment]
두가지 방법이 있어요. 
단순하게 1번부터 다운받는다. 시간이 오래걸리는 단점이 있고 순서가 엉키기기에 필요한 부분만 골라내야하죠.

다른 하나는....1000으로 다운을 시도하면 제일 마지막 화수를 다운받습니다. 만약 최신 화수가 1076화인데 다운로드 1000을 입력하면 1000화가 아닌 1076화를 다운받죠. 
내가 1052화까지 받은터라 1053부터가 필요하다면 1076-1052 = 24 내가 못본 화수가 24화군요. 1000까지만 입력이 되는데 여기서 -24를 해서 976을 입력하면? 1053화부터 다운이 되어야하지만 1052부터 다운을 하네요. 
첫회 게시물에 0화부터 시작이라서 화수차이가 1이 나는군요 ㅎ
 이정도면 적당히 조절해서 쓸수 있겟즁?

**Comment by yeorinhieut** [comment]
일단 다음 릴리즈(언젠진 모르겠어요.. 아무나 기여해주시면 감사합니다)에 대응 해보도록 하겠습니다

**Comment by yeorinhieut** [comment]
v1.0.0 릴리즈에 다중 페이지 지원 기능을 추가하였습니다.
