### ISSUE TITLE
사용방법 문의 드립니다

### ISSUE THREAD

**Issue by garkasa1** [yeorinhieut/novel-dl#25]
북마크에 자바스크립트 등록 - 뉴토끼 소설 중 다운받고싶은 소설의 목록에 들어감 - 변경한 북마크를 클릭하면 작동

인 것 같은데 클릭하면 다운로드 시작 회차 누르라고 하고, 누르면 그 이후 반응이 없습니다.

그리고 다운로드가 된다면 걸리는 시간 / 저장 경로가 표기가 안되어있는데

어디로 저장이 되는걸까요? 다운이 안되더니 마나토끼 북토끼 등 403 forbidden이 뜹니다. 아마 차단먹은것같습니다.,

**Comment by yeorinhieut** [comment]
저장은 다운이 다 완료되었을 시, 브라우저에서 다운로드 됩니다(사진 다운과 동일하게!) 반응이 없는건 기다리시면 나올것 같은데 사진 첨부 부탁드리겠습니다. 또한 다운로드와 동시에 다른 작업을 수행하시면 초당 1회 요청을 초과하기 때문에 403 Forbidden이 1시간 가량 뜰 수 있습니다.

**Comment by garkasa1** [comment]
> 저장은 다운이 다 완료되었을 시, 브라우저에서 다운로드 됩니다(사진 다운과 동일하게!) 반응이 없는건 기다리시면 나올것 같은데 사진 첨부 부탁드리겠습니다. 또한 다운로드와 동시에 다른 작업을 수행하시면 초당 1회 요청을 초과하기 때문에 403 Forbidden이 1시간 가량 뜰 수 있습니다.

![제목 없음](https://github.com/yeorinhieut/novel-dl/assets/96948820/a0c8f61b-72b2-40c4-ac38-6b5a9285d75e)

처음에 시도하면 총 회차수 기입 -> 825 기입
몇회차부터 다운 시작할거냐고 5분정도 뒤에 뜸 - > 1 기입

이후에 저렇게 에러가 뜹니다
- An error occurred. Please check the console for details.

뭐가 문제일까요?
그리고 총 몇회까지 있는거 다운받을까요 기입후 몇화부터 다운받을까요 기입하는거 뜨는게 4~5분 넘게 걸리던데
뭐가 문제인걸까요?

**Comment by yeorinhieut** [comment]
아 처음엔 회차수가 아니라 소설이 몇 페이지까지 있는지(1000화를 넘어가면 북토끼에선 2페이지로 처리됩니다) 기입하는 과정입니다. 혼동이 있을 수 있는데 실수했네요.. 1000화 이하는 1이라고 적어주시면 됩니다

**Comment by garkasa1** [comment]
> 아 처음엔 회차수가 아니라 소설이 몇 페이지까지 있는지(1000화를 넘어가면 북토끼에선 2페이지로 처리됩니다) 기입하는 과정입니다. 혼동이 있을 수 있는데 실수했네요.. 1000화 이하는 1이라고 적어주시면 됩니다

아하 말씀해주신 대로 처음 825 대신 1 기입하니까 잘 해결되었습니다. 감사합니다!
