### ISSUE TITLE
북마크 사용중 속도가 빨라 다운로드 중간 차단당합니다...

### ISSUE THREAD

**Issue by healthy2553** [yeorinhieut/novel-dl#27]
혹시 방법이 있을까요..?

**Comment by yeorinhieut** [comment]
현재 두 소설을 동시에 받지 않는이상 차단은 안당하는 것으로 알고있는데.. 테스트 후 딜레이 추가 해보겠습니다

**Comment by yeorinhieut** [comment]
현재 두 소설을 동시에 받지 않는이상 차단은 안당하는 것으로 알고있는데.. 테스트 후 딜레이 추가 해보겠습니다

**Comment by yeorinhieut** [comment]
동시 다운이 아닌 한 정상 작동하고 있습니다.
