### ISSUE TITLE
북마크 사용시 저장 위치는 커스터마이징이 안되는건가요?

### ISSUE THREAD

**Issue by GregHKim** [yeorinhieut/novel-dl#28]
코드가 작동은 하는것 같은데 저장 위치를 찾을 수가 없네요... 
어디서 볼 수 있을까요?

**Comment by yeorinhieut** [comment]
다 다운시 브라우저에서 일반 파일들을 받는것과 같이 다운로드됩니다. 아마 다운로드 폴더에 있을듯 하네요
