### ISSUE TITLE
북토끼측에서 업데이트를 한건지 다운로드가 항상 60-70%에서 멈춥니다

### ISSUE THREAD

**Issue by miuna00** [yeorinhieut/novel-dl#29]
이 다운로더 말고 다른 다운로더도 다 멈추네요 vpn으로 ip 바꿔도 동일증상입니다.

**Comment by yeorinhieut** [comment]
체크 해보겠습니다 아마 캡챠가 이번에 다시 들어가서 그거때문 같기도 하네요. 수정 한번 해보겠습니다

**Comment by yeorinhieut** [comment]
어느 소설에서 해당 이슈가 발생하는지 알려주실 수 있나요?

**Comment by miuna00** [comment]
> 어느 소설에서 해당 이슈가 발생하는지 알려주실 수 있나요?

빠른 답변 감사드립니다. 이 작품입니다. https://booktoki460.com/novel/14323569

**Comment by yeorinhieut** [comment]
수정 완료했습니다. 캡챠 발견시, 수동으로 사용자가 캡챠를 새 창에서 해제하고 확인을 누르면 다운로드가 재개됩니다.
