### ISSUE TITLE
2000화까지만 지원이 되는건가요?

### ISSUE THREAD

**Issue by hoonsoft** [yeorinhieut/novel-dl#3]
2000화가 넘는 작품의 경우 맨뒤에서 부터 2000화가 되는 것 까지만 다운이되는데
혹시 특정 회차 부분만 따로 받는 방법이 있을까요?

**Comment by yeorinhieut** [comment]
2000화가 넘는 작품 링크 부탁드립니다.

**Comment by hoonsoft** [comment]
https://booktoki317.com/novel/1793238

**Comment by hoonsoft** [comment]
> 2000화가 넘는 작품 링크 부탁드립니다.

https://booktoki317.com/novel/1793238
