### ISSUE TITLE
중간 회차부터 끝회차까지 다운받는 방법

### ISSUE THREAD

**Issue by Damnuuu** [yeorinhieut/novel-dl#30]
가능할까요?
1000회 2000회가 넘어가는 소설들은 몇달에 한번씩 보는 편인데
1회부터 다시 받기에는 오래걸려서 혹시 중간부터 가능한지 문의합니다. :)

**Comment by yeorinhieut** [comment]
현재 프로그램에 시작할 회차를 입력하는 부분이 있습니다
