### ISSUE TITLE
북토끼 다운로더 사용시 아이디 밴당합니다

### ISSUE THREAD

**Issue by shootmg50** [yeorinhieut/novel-dl#31]
저도 이런걸로 밴 당할줄은 몰랐네요. 여러번 접속해서 서버 과부화하는  id잡아내서 밴하는것 같습니다.
매번 로그아웃하고 하다가 이번에 걸렸네요.

**Comment by yeorinhieut** [comment]
비로그인시 정상 사용 확인되었습니다. 로그인 사용은 좀 위험할듯 하네요.
