### ISSUE TITLE
개별다운(링크직접입력) 기능제안

### ISSUE THREAD

**Issue by wheatflor** [yeorinhieut/novel-dl#5]
(이미 글을 읽으셨을 수도 있지만 서술이 난잡하여 좀 정리를 했습니다.
내용 자체는 똑같으니 읽으셨다면 수정사항에 대해 신경쓰지 않으셔도 됩니다.)

links.txt의 링크를 직접 입력해서 다운로드 하는 방식으로도 동작하는 기능도 넣으면 어떨까요?

혹시 특정 화가 안받아지거나, 오류등의 문제로 추후에 재 다운로드를 해야할 때 유용하며, 오류가 나는 페이지가 있을 때 해당 페이지만 테스트하기에 좋을거 같아서 있으면 좋을거 같더라고요.
아마 개발자분은 테스트목적으로 그렇게 이미 쓰고있으실 수도 있긴한데, 이용자측에서 문제 식별 후 보고를 위해서 간단한 테스트를 해볼 수도 있으면 좋겠다 싶어서 제안드렸습니다.

//// 제안과 무관한 내용입니다.
이번 업데이트에 줄바꿈 이슈가 해결되었다고 해서 한번 테스트 해봤으며, 해결이 안된 것으로 확인됩니다.
이슈 해결을 요청드리는건 아니고, 이번에 시도해보시고 해결이 안된거니 원인이 다양하다는 것 일테고 나중에 해결하실 마음이 들 때 비교할 대상이 필요하시지 않을까 싶어서 작성했습니다.

https://github.com/yeorinhieut/novel-dl/releases/tag/v0.1.2
해당버전 안내에 나온 #2 이슈와 같은 증상이며

#1  증상도 있던 페이지라 이번 릴리즈에 안내된 html 다운로드 방식을 취했다는 특이사항이 있습니다.

발생링크는 https://booktoki318.com/novel/7140647?book=%EC%84%B1%EC%9D%B8%EC%86%8C%EC%84%A4와 https://booktoki318.com/novel/7140797?book=%EC%84%B1%EC%9D%B8%EC%86%8C%EC%84%A4&spage=1입니다.

그리고 별건 아닌데  <452화> 같이 <>안에 들어간 단어가 사라지는 현상이 있네요.
앞서 설명한 이슈랑 연관성은 없어보이지만 가끔 소설 따라서는 <>를 독백이나 기타 용도로 쓰는 경우도 있으니 생각보다 중요한 문제가 아닐까 싶어 이부분도 적어봤습니다.

**Comment by yeorinhieut** [comment]
줄바꿈은 멍청한 제가 전에 빌드한 파일을 올려서 업데이트되지 않은걸로 보입니다.. release에 새로 업로드 했습니다. #6 
<> 관련 문제는 파악중에 있습니다
