### ISSUE TITLE
build 이후에도 줄바꿈 개선사항 적용되지 않음 해결법

### ISSUE THREAD

**Issue by Hayebeom** [yeorinhieut/novel-dl#8]
아침에 이슈 확인해주신 것 이후에 실행해봤으나 같은 문제점 확인하여 코드 테스트 했습니다.

text = strings.ReplaceAll(text, "\<br\>", "\n")
해당 이슈 코드를

text = strings.ReplaceAll(text, "\<br/\>", "\n")
로 변경해야 작동하는 것을 확인했습니다. (아쉽게도 "대화" 마다 줄바꿈은 불가능했습니다)

확인 후 rebuild 부탁드리겠습니다. 
감사합니다.

**Comment by yeorinhieut** [comment]
수정 완료했습니다! 감사합니다
