### ISSUE TITLE
다운로드 시작 회차 입력 기능 추가

### ISSUE THREAD

**Issue by brad0120** [yeorinhieut/novel-dl#9]
구글링 해서 여기까지 왔습니다. 
정말 고맙게 잘 쓰고 있어요.
회차가 긴 목록들도 통으로 받아야 해서 불편한 부분이 있는데
다운로드 시작 회차도 입력 가능했으면 아주 좋을 것 같습니다.
특정 구간부터 다운 시작이 되면 시간 절약이 몇 배나 될 것 같네요.
감사합니다.

**Comment by yeorinhieut** [comment]
의견 감사합니다! Todo에 추가하겠습니다

**Comment by yeorinhieut** [comment]
완료
